apiVersion: apps/v1
kind: Deployment
metadata:
  name: roamio
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: roamio
  template:
    metadata:
      labels:
        app: roamio
    spec:
      containers:
      - name: back-end
        image: roamio:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: PGHOST
          value: "host.docker.internal"
        - name: PGUSER
          value: "postgres"
        - name: PGPASSWORD
          value: "postgres"
        - name: PGDATABASE
          value: "mydb"
        - name: PGPORT
          value: "5432"
---
apiVersion: v1
kind: Service
metadata:
  name: go-backend-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: go-backend
  ports:
  - port: 8080
    targetPort: 8080
